openapi: 3.0.0
info:
  title: Cryptocurrency Exchange API
  description: API for finding the best cryptocurrency exchange rates
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: Development server

paths:
  /exchange-routing:
    get:
      summary: Get the best cryptocurrency exchange rate
      description: Retrieve the best exchange rate for a given cryptocurrency.
      parameters:
        - in: query
          name: symbol
          required: true
          description: Symbol of the cryptocurrency (e.g., BTC, ETH, SOL)
          schema:
            type: string
        - in: query
          name: amount
          required: true
          description: Amount of cryptocurrency to exchange
          schema:
            type: number
      responses:
        '200':
          description: Successful response with the best exchange rate information
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                  cryptoAmount:
                    type: number
                  usdAmount:
                    type: number
                  exchange:
                    type: string
        '400':
          description: Bad request response when query parameters are invalid
  /api/cryptos:
    get:
      summary: Retrieve a list of cryptocurrencies
      description: Fetches a list of cryptocurrencies sorted by market cap in descending order from the CoinGecko API.
      responses:
        '200':
          description: A list of cryptocurrencies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier for the cryptocurrency.
                    symbol:
                      type: string
                      description: The symbol of the cryptocurrency.
                    name:
                      type: string
                      description: The name of the cryptocurrency.
                    current_price:
                      type: number
                      description: The current price of the cryptocurrency.
                    market_cap:
                      type: number
                      description: The market capitalization of the cryptocurrency.
                    market_cap_rank:
                      type: number
                      description: The rank of the cryptocurrency by market capitalization.
                    total_volume:
                      type: number
                      description: The total volume of the cryptocurrency traded in the last 24 hours.
                    high_24h:
                      type: number
                      description: The highest price of the cryptocurrency in the last 24 hours.
                    low_24h:
                      type: number
                      description: The lowest price of the cryptocurrency in the last 24 hours.
                    price_change_24h:
                      type: number
                      description: The price change of the cryptocurrency in the last 24 hours.
                    price_change_percentage_24h:
                      type: number
                      description: The percentage change in the price of the cryptocurrency in the last 24 hours.
        '500':
          description: Error fetching data from CoinGecko